name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
    - name: vuemall deploy
      uses: easingthemes/ssh-deploy@v2.0.8
      with:
        # Private Key
        SSH_PRIVATE_KEY: ${{secrets.ALIYUN}}
        # Remote host
        REMOTE_HOST: "47.105.218.103"
        # Remote user
        REMOTE_USER:  "root"
        # Remote port
        REMOTE_PORT: 22
        # Source directory
        SOURCE: "/dist"
        # Target directory
        TARGET: "/root/vueProject/"
